from setuptools import setup

setup(
    name='food_hygiene_search',
    version='0.1',
    packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.pip',
              'venv.lib.python2.7.site-packages.pip._vendor', 'venv.lib.python2.7.site-packages.pip._vendor.idna',
              'venv.lib.python2.7.site-packages.pip._vendor.pep517',
              'venv.lib.python2.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python2.7.site-packages.pip._vendor.certifi',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pip._internal', 'venv.lib.python2.7.site-packages.pip._internal.cli',
              'venv.lib.python2.7.site-packages.pip._internal.req',
              'venv.lib.python2.7.site-packages.pip._internal.vcs',
              'venv.lib.python2.7.site-packages.pip._internal.utils',
              'venv.lib.python2.7.site-packages.pip._internal.models',
              'venv.lib.python2.7.site-packages.pip._internal.commands',
              'venv.lib.python2.7.site-packages.pip._internal.operations', 'venv.lib.python2.7.site-packages.idna',
              'venv.lib.python2.7.site-packages.click', 'venv.lib.python2.7.site-packages.flask',
              'venv.lib.python2.7.site-packages.flask.json', 'venv.lib.python2.7.site-packages.wheel',
              'venv.lib.python2.7.site-packages.wheel.cli', 'venv.lib.python2.7.site-packages.jinja2',
              'venv.lib.python2.7.site-packages.certifi', 'venv.lib.python2.7.site-packages.chardet',
              'venv.lib.python2.7.site-packages.chardet.cli', 'venv.lib.python2.7.site-packages.MySQLdb',
              'venv.lib.python2.7.site-packages.MySQLdb.constants', 'venv.lib.python2.7.site-packages.urllib3',
              'venv.lib.python2.7.site-packages.urllib3.util', 'venv.lib.python2.7.site-packages.urllib3.contrib',
              'venv.lib.python2.7.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python2.7.site-packages.urllib3.packages',
              'venv.lib.python2.7.site-packages.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.wtforms', 'venv.lib.python2.7.site-packages.wtforms.ext',
              'venv.lib.python2.7.site-packages.wtforms.ext.csrf', 'venv.lib.python2.7.site-packages.wtforms.ext.i18n',
              'venv.lib.python2.7.site-packages.wtforms.ext.django',
              'venv.lib.python2.7.site-packages.wtforms.ext.django.templatetags',
              'venv.lib.python2.7.site-packages.wtforms.ext.dateutil',
              'venv.lib.python2.7.site-packages.wtforms.ext.appengine',
              'venv.lib.python2.7.site-packages.wtforms.ext.sqlalchemy',
              'venv.lib.python2.7.site-packages.wtforms.csrf', 'venv.lib.python2.7.site-packages.wtforms.fields',
              'venv.lib.python2.7.site-packages.wtforms.widgets', 'venv.lib.python2.7.site-packages.requests',
              'venv.lib.python2.7.site-packages.werkzeug', 'venv.lib.python2.7.site-packages.werkzeug.debug',
              'venv.lib.python2.7.site-packages.werkzeug.contrib', 'venv.lib.python2.7.site-packages.flask_wtf',
              'venv.lib.python2.7.site-packages.flask_wtf.recaptcha', 'venv.lib.python2.7.site-packages.markupsafe',
              'venv.lib.python2.7.site-packages.setuptools', 'venv.lib.python2.7.site-packages.setuptools.extern',
              'venv.lib.python2.7.site-packages.setuptools._vendor',
              'venv.lib.python2.7.site-packages.setuptools._vendor.packaging',
              'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages.sqlalchemy',
              'venv.lib.python2.7.site-packages.sqlalchemy.ext',
              'venv.lib.python2.7.site-packages.sqlalchemy.ext.declarative',
              'venv.lib.python2.7.site-packages.sqlalchemy.orm', 'venv.lib.python2.7.site-packages.sqlalchemy.sql',
              'venv.lib.python2.7.site-packages.sqlalchemy.util', 'venv.lib.python2.7.site-packages.sqlalchemy.event',
              'venv.lib.python2.7.site-packages.sqlalchemy.engine',
              'venv.lib.python2.7.site-packages.sqlalchemy.testing',
              'venv.lib.python2.7.site-packages.sqlalchemy.testing.suite',
              'venv.lib.python2.7.site-packages.sqlalchemy.testing.plugin',
              'venv.lib.python2.7.site-packages.sqlalchemy.dialects',
              'venv.lib.python2.7.site-packages.sqlalchemy.dialects.mssql',
              'venv.lib.python2.7.site-packages.sqlalchemy.dialects.mysql',
              'venv.lib.python2.7.site-packages.sqlalchemy.dialects.oracle',
              'venv.lib.python2.7.site-packages.sqlalchemy.dialects.sqlite',
              'venv.lib.python2.7.site-packages.sqlalchemy.dialects.sybase',
              'venv.lib.python2.7.site-packages.sqlalchemy.dialects.firebird',
              'venv.lib.python2.7.site-packages.sqlalchemy.dialects.postgresql',
              'venv.lib.python2.7.site-packages.sqlalchemy.databases',
              'venv.lib.python2.7.site-packages.sqlalchemy.connectors', 'venv.lib.python2.7.site-packages.itsdangerous',
              'venv.lib.python2.7.site-packages.pkg_resources', 'venv.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python2.7.site-packages.flask_sqlalchemy', 'application', 'application.models'],
    url='',
    license='',
    author='deanrobinson',
    author_email='dean.robinson@icloud.com',
    description=''
)
